// @/contexts/IntlProvider.tsx
// Wraps react-intl's IntlProvider, reading the current L1 locale from LanguageContext.
// Messages loaded from packages/shared/locales/ (generated by sync-translations.mjs).

import React, { ReactNode, useMemo } from 'react';
import { IntlProvider as ReactIntlProvider } from 'react-intl';
import { useLanguage } from './LanguageContext';
import { loadLocaleMessages } from '@/src/i18n/load-messages';

export const IntlProviderWrapper: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { l1Lang } = useLanguage();
  const locale = l1Lang?.code ?? 'en';

  const messages = useMemo(() => {
    try {
      return loadLocaleMessages(locale);
    } catch {
      // Fallback to English if the locale file is missing
      return loadLocaleMessages('en');
    }
  }, [locale]);

  return (
    <ReactIntlProvider
      locale={locale}
      messages={messages}
      defaultLocale="en"
      onError={(err) => {
        // Suppress MISSING_TRANSLATION in development — the useT() hook
        // already falls back to showing the key name. Without this handler,
        // react-intl throws these as errors which crash the error boundary.
        if (err.code !== 'MISSING_TRANSLATION') {
          console.error(err);
        }
      }}
    >
      {children}
    </ReactIntlProvider>
  );
};
