import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { getLocale, getMessages, getTimeZone } from 'next-intl/server';
import { ThemeProvider } from '@/components/theme-provider';
import { LocaleProvider } from '@/providers/locale-provider';
import { SessionProvider } from '@/providers/session-provider';
import { ApiClientProvider } from '@/components/api-client-provider';
import { UserDataProvider } from '@/providers/user-data-provider';
import { SavedWordsProvider } from '@/providers/saved-words-provider';
import { SubscriptionProvider } from '@/providers/subscription-provider';
import SupabaseSessionHandler from '@/components/auth/supabase-session-handler';
import { CapacitorRedirect } from '@/components/layout/capacitor-redirect';
import { PublicHeader } from '@/components/layout/public-header';
import { Toaster } from '@/components/ui/sonner';
import ogVideos from '@/data/og-videos.json';
import './globals.css';

// Inter is vendored locally (src/app/fonts/) so builds never fetch Google
// Fonts at build time; this keeps `next build` working in sandboxed/offline
// environments. next/font/local requires the files inside the app directory,
// so the same TTFs are also vendored in apps/mobile/assets/fonts/.
const inter = localFont({
  src: [
    { path: './fonts/Inter_400Regular.ttf', weight: '400', style: 'normal' },
    { path: './fonts/Inter_500Medium.ttf', weight: '500', style: 'normal' },
    { path: './fonts/Inter_600SemiBold.ttf', weight: '600', style: 'normal' },
    { path: './fonts/Inter_700Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-inter',
});

const SITE_NAME = 'Language Player';
const SITE_DESCRIPTION =
  'Watch videos, live TV, and TV shows with interactive dual subtitles. Look up any word, read, and review with spaced repetition. Learn 200+ languages naturally.';
const SITE_URL =
  process.env.AUTH_URL || 'https://language-player.netlify.app';
const OG_IMAGE = '/og'; // fallback: logo-only OG image

/** Read pre-computed OG video IDs from the cached JSON file.
 *  Generated by scripts/generate-og-cache.mjs — run it periodically
 *  to refresh with current popular videos. */
function getOgVideoIds(l2 = 'en'): string[] {
  const ids = (ogVideos as Record<string, string[]>)[l2];
  return ids?.slice(0, 4) ?? [];
}

export async function generateMetadata(): Promise<Metadata> {
  const videoIds = getOgVideoIds('en');

  let ogImageUrl = OG_IMAGE; // fallback: logo + wordmark
  if (videoIds.length > 0) {
    ogImageUrl = `/og?videos=${videoIds.join(',')}&lang=English`;
  }

  const defaultTitle = `${SITE_NAME} — Learn languages through video`;

  return {
    metadataBase: new URL(SITE_URL),
    title: defaultTitle,
    description: SITE_DESCRIPTION,
    keywords: ['language learning', 'subtitles', 'dictionary', 'video', 'immersion'],
    // Open Graph (Facebook, LinkedIn, Discord, etc.)
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      locale: 'en_US',
      url: SITE_URL,
      title: `${SITE_NAME} — Learn languages through video`,
      description: SITE_DESCRIPTION,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: `${SITE_NAME} — Learn languages through video`,
        },
      ],
    },
    // Twitter / X Cards
    twitter: {
      card: 'summary_large_image',
      site: '@langplayer',
      title: `${SITE_NAME} — Learn languages through video`,
      description: SITE_DESCRIPTION,
      images: [ogImageUrl],
    },
    icons: {
      icon: [
        { url: '/favicon.ico' },
        { url: '/favicon-16.png', sizes: '16x16', type: 'image/png' },
        { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
        { url: '/favicon-48.png', sizes: '48x48', type: 'image/png' },
        { url: '/favicon-96.png', sizes: '96x96', type: 'image/png' },
        { url: '/favicon-128.png', sizes: '128x128', type: 'image/png' },
        { url: '/favicon-192.png', sizes: '192x192', type: 'image/png' },
        { url: '/favicon-512.png', sizes: '512x512', type: 'image/png' },
      ],
      apple: [
        { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
      ],
    },
  };
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  const messages = await getMessages();
  const timeZone = await getTimeZone();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/* Preconnect to YouTube for faster iframe embed */}
        <link rel="preconnect" href="https://www.youtube.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://i.ytimg.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://www.youtube.com" />
      </head>
      <body className={`${inter.variable} font-sans`}>
        <LocaleProvider locale={locale} messages={messages} timeZone={timeZone}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <SessionProvider>
              <ApiClientProvider>
                <UserDataProvider>
                  <SavedWordsProvider>
                    <SubscriptionProvider>
                      <SupabaseSessionHandler />
                      <CapacitorRedirect />
                      <PublicHeader />
                      {children}
                    </SubscriptionProvider>
                  </SavedWordsProvider>
                </UserDataProvider>
              </ApiClientProvider>
            </SessionProvider>
            <Toaster richColors closeButton={false} position="top-center" />
          </ThemeProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
