#!/usr/bin/env python3
"""Fill all missing translations across 29 languages."""
import json, os

MSG = os.path.join(os.path.dirname(__file__), '..', 'messages')

# Translation data: {category: {key: {lang: value, ...}}}
# Each key maps language codes to translations
T = {
    "title": {
        "explore_media": {"af":"Verken media","ar":"استكشاف الوسائط","ca":"Explorar contingut","de":"Medien entdecken","el":"Εξερεύνηση πολυμέσων","fi":"Tutki mediaa","fr":"Explorer les médias","ga":"Fiosraigh na meáin","hi":"मीडिया अन्वेषण करें","hr":"Istraži medije","hu":"Média felfedezése","id":"Jelajahi Media","it":"Esplora i media","ja":"メディアを探索","ko":"미디어 탐색","nl":"Media verkennen","no":"Utforsk medier","pl":"Odkrywaj media","pt":"Explorar mídia","ro":"Explorează media","ru":"Обзор медиа","sr":"Истражи медије","sv":"Utforska media","sw":"Chunguza midia","th":"สำรวจสื่อ","tr":"Medyayı Keşfet","vi":"Khám phá phương tiện","zh-Hans":"探索媒体","zh-Hant":"探索媒體"},
        "explore": {"af":"Verken","ar":"استكشاف","ca":"Explorar","de":"Entdecken","el":"Εξερεύνηση","fi":"Tutki","fr":"Explorer","ga":"Fiosraigh","hi":"अन्वेषण करें","hr":"Istraži","hu":"Felfedezés","id":"Jelajahi","it":"Esplora","ja":"探索","ko":"탐색","nl":"Verkennen","no":"Utforsk","pl":"Odkrywaj","pt":"Explorar","ro":"Explorează","ru":"Обзор","sr":"Истражи","sv":"Utforska","sw":"Chunguza","th":"สำรวจ","tr":"Keşfet","vi":"Khám phá","zh-Hans":"探索","zh-Hant":"探索"},
        "welcome_back": {"af":"Welkom terug","ar":"مرحبًا بعودتك","ca":"Benvingut de nou","de":"Willkommen zurück","el":"Καλώς ήρθατε ξανά","fi":"Tervetuloa takaisin","fr":"Bon retour","ga":"Fáilte ar ais","hi":"वापसी पर स्वागत है","hr":"Dobrodošli natrag","hu":"Üdvözöljük újra","id":"Selamat datang kembali","it":"Bentornato","ja":"おかえりなさい","ko":"다시 오신 것을 환영합니다","nl":"Welkom terug","no":"Velkommen tilbake","pl":"Witaj z powrotem","pt":"Bem-vindo de volta","ro":"Bine ai revenit","ru":"С возвращением","sr":"Добродошли назад","sv":"Välkommen tillbaka","sw":"Karibu tena","th":"ยินดีต้อนรับกลับ","tr":"Tekrar hoş geldiniz","vi":"Chào mừng trở lại","zh-Hans":"欢迎回来","zh-Hant":"歡迎回來"},
        "create_account": {"af":"Skep jou rekening","ar":"أنشئ حسابك","ca":"Crea el teu compte","de":"Konto erstellen","el":"Δημιουργήστε τον λογαριασμό σας","fi":"Luo tilisi","fr":"Créez votre compte","ga":"Cruthaigh do chuntas","hi":"अपना खाता बनाएं","hr":"Stvorite svoj račun","hu":"Hozza létre fiókját","id":"Buat akun Anda","it":"Crea il tuo account","ja":"アカウントを作成","ko":"계정 만들기","nl":"Maak uw account aan","no":"Opprett kontoen din","pl":"Utwórz swoje konto","pt":"Crie sua conta","ro":"Creează-ți contul","ru":"Создайте аккаунт","sr":"Направите свој налог","sv":"Skapa ditt konto","sw":"Unda akaunti yako","th":"สร้างบัญชีของคุณ","tr":"Hesabınızı oluşturun","vi":"Tạo tài khoản của bạn","zh-Hans":"创建您的账户","zh-Hant":"建立您的帳戶"},
        "welcome": {"af":"Welkom by Language Player","ar":"مرحبًا بك في Language Player","ca":"Benvingut a Language Player","de":"Willkommen bei Language Player","el":"Καλώς ήρθατε στο Language Player","fi":"Tervetuloa Language Playeriin","fr":"Bienvenue sur Language Player","ga":"Fáilte go Language Player","hi":"Language Player में आपका स्वागत है","hr":"Dobrodošli u Language Player","hu":"Üdvözöljük a Language Playerben","id":"Selamat datang di Language Player","it":"Benvenuto su Language Player","ja":"Language Player へようこそ","ko":"Language Player에 오신 것을 환영합니다","nl":"Welkom bij Language Player","no":"Velkommen til Language Player","pl":"Witaj w Language Player","pt":"Bem-vindo ao Language Player","ro":"Bun venit la Language Player","ru":"Добро пожаловать в Language Player","sr":"Добродошли у Language Player","sv":"Välkommen till Language Player","sw":"Karibu kwenye Language Player","th":"ยินดีต้อนรับสู่ Language Player","tr":"Language Player'a hoş geldiniz","vi":"Chào mừng đến với Language Player","zh-Hans":"欢迎来到 Language Player","zh-Hant":"歡迎來到 Language Player"},
        "check_email": {"af":"Gaan jou e-pos na","ar":"تحقق من بريدك الإلكتروني","ca":"Revisa el teu correu","de":"Überprüfen Sie Ihre E-Mail","el":"Ελέγξτε το email σας","fi":"Tarkista sähköpostisi","fr":"Vérifiez votre e-mail","ga":"Seiceáil do ríomhphost","hi":"अपना ईमेल जांचें","hr":"Provjerite svoju e-poštu","hu":"Ellenőrizze az e-mailjét","id":"Periksa email Anda","it":"Controlla la tua email","ja":"メールを確認してください","ko":"이메일을 확인하세요","nl":"Controleer uw e-mail","no":"Sjekk e-posten din","pl":"Sprawdź swoją skrzynkę e-mail","pt":"Verifique seu e-mail","ro":"Verifică-ți emailul","ru":"Проверьте почту","sr":"Проверите своју е-пошту","sv":"Kontrollera din e-post","sw":"Angalia barua pepe yako","th":"ตรวจสอบอีเมลของคุณ","tr":"E-postanızı kontrol edin","vi":"Kiểm tra email của bạn","zh-Hans":"查看您的邮箱","zh-Hant":"查看您的電子郵件"},
        "reset_password": {"af":"Stel wagwoord terug","ar":"إعادة تعيين كلمة المرور","ca":"Restablir contrasenya","de":"Passwort zurücksetzen","el":"Επαναφορά κωδικού","fi":"Palauta salasana","fr":"Réinitialiser le mot de passe","ga":"Athshocraigh pasfhocal","hi":"पासवर्ड रीसेट करें","hr":"Resetiraj lozinku","hu":"Jelszó visszaállítása","id":"Atur ulang kata sandi","it":"Reimposta password","ja":"パスワードをリセット","ko":"비밀번호 재설정","nl":"Wachtwoord opnieuw instellen","no":"Tilbakestill passord","pl":"Zresetuj hasło","pt":"Redefinir senha","ro":"Resetează parola","ru":"Сбросить пароль","sr":"Ресетуј лозинку","sv":"Återställ lösenord","sw":"Weka upya nenosiri","th":"รีเซ็ตรหัสผ่าน","tr":"Şifrenizi sıfırlayın","vi":"Đặt lại mật khẩu","zh-Hans":"重置密码","zh-Hant":"重設密碼"},
        "i_speak": {"af":"Ek praat","ar":"أتحدث","ca":"Parlo","de":"Ich spreche","el":"Μιλάω","fi":"Puhun","fr":"Je parle","ga":"Labhraím","hi":"मैं बोलता हूँ","hr":"Govorim","hu":"Beszélek","id":"Saya berbicara","it":"Parlo","ja":"話せる言語","ko":"할 수 있는 언어","nl":"Ik spreek","no":"Jeg snakker","pl":"Mówię","pt":"Eu falo","ro":"Vorbesc","ru":"Я говорю","sr":"Говорим","sv":"Jag talar","sw":"Ninazungumza","th":"ฉันพูด","tr":"Konuşuyorum","vi":"Tôi nói","zh-Hans":"我会说","zh-Hant":"我會說"},
        "i_learning": {"af":"Ek leer","ar":"أتعلم","ca":"Estic aprenent","de":"Ich lerne","el":"Μαθαίνω","fi":"Opettelen","fr":"J'apprends","ga":"Tá mé ag foghlaim","hi":"मैं सीख रहा हूँ","hr":"Učim","hu":"Tanulok","id":"Saya belajar","it":"Sto imparando","ja":"学習中の言語","ko":"배우는 언어","nl":"Ik leer","no":"Jeg lærer","pl":"Uczę się","pt":"Estou aprendendo","ro":"Învăț","ru":"Я изучаю","sr":"Учим","sv":"Jag lär mig","sw":"Ninajifunza","th":"ฉันกำลังเรียน","tr":"Öğreniyorum","vi":"Tôi đang học","zh-Hans":"我正在学","zh-Hant":"我正在學"},
        "confirm_in_app_purchase": {"af":"Bevestig jou inprogram-aankoop","ar":"تأكيد الشراء داخل التطبيق","ca":"Confirma la teva compra dins de l'app","de":"In-App-Kauf bestätigen","el":"Επιβεβαιώστε την αγορά εντός εφαρμογής","fi":"Vahvista sovelluksen sisäinen ostoksesi","fr":"Confirmer votre achat intégré","ga":"Deimhnigh do cheannachán in-app","hi":"अपनी इन-ऐप खरीदारी की पुष्टि करें","hr":"Potvrdite kupnju unutar aplikacije","hu":"Erősítse meg az alkalmazáson belüli vásárlást","id":"Konfirmasi Pembelian Dalam Aplikasi Anda","it":"Conferma il tuo acquisto in-app","ja":"アプリ内購入を確認","ko":"인앱 구매 확인","nl":"Bevestig uw in-app aankoop","no":"Bekreft kjøpet ditt i appen","pl":"Potwierdź zakup w aplikacji","pt":"Confirmar sua compra no app","ro":"Confirmați achiziția în aplicație","ru":"Подтвердите встроенную покупку","sr":"Потврдите куповину унутар апликације","sv":"Bekräfta ditt köp i appen","sw":"Thibitisha ununuzi wako wa ndani ya programu","th":"ยืนยันการซื้อในแอปของคุณ","tr":"Uygulama İçi Satın Almanızı Onaylayın","vi":"Xác nhận mua trong ứng dụng","zh-Hans":"确认您的应用内购买","zh-Hant":"確認您的應用內購買"},
        "only_lifetime_available": {"af":"Slegs die Lewenslange Plan is in die App Store beskikbaar","ar":"فقط الخطة مدى الحياة متاحة في App Store","ca":"Només el Pla Vitalici està disponible a l'App Store","de":"Nur der Lifetime-Plan ist im App Store verfügbar","el":"Μόνο το Ισόβιο Πρόγραμμα είναι διαθέσιμο στο App Store","fi":"Vain Elinikäinen Sopimus on saatavilla App Storessa","fr":"Seul le Plan à Vie est disponible sur l'App Store","ga":"Níl ach an Plean Saoil ar fáil san App Store","hi":"App Store में केवल आजीवन योजना उपलब्ध है","hr":"Samo je Doživotni Plan dostupan u App Storeu","hu":"Csak az Élettartam Csomag érhető el az App Store-ban","id":"Hanya Paket Seumur Hidup yang tersedia di App Store","it":"Solo il Piano a Vita è disponibile nell'App Store","ja":"App Storeではライフタイムプランのみ利用可能","ko":"App Store에서 평생 플랜만 이용 가능","nl":"Alleen het Levenslang Abonnement is beschikbaar in de App Store","no":"Kun Livstidsplanen er tilgjengelig i App Store","pl":"Tylko Plan Dożywotni jest dostępny w App Store","pt":"Apenas o Plano Vitalício está disponível na App Store","ro":"Doar Planul pe Viață este disponibil în App Store","ru":"В App Store доступен только Пожизненный план","sr":"Само је Доживотни План доступан у App Store-у","sv":"Endast livstidsplanen är tillgänglig i App Store","sw":"Mpango wa Maisha pekee ndio unaopatikana kwenye App Store","th":"เฉพาะแผนตลอดชีพเท่านั้นที่มีใน App Store","tr":"App Store'da yalnızca Ömür Boyu Plan mevcut","vi":"Chỉ có Gói Trọn Đời khả dụng trên App Store","zh-Hans":"App Store 中仅提供终身计划","zh-Hant":"App Store 中僅提供終身計劃"},
    },
    "action": {
        "forgot_password": {"af":"Wagwoord vergeet?","ar":"نسيت كلمة المرور؟","ca":"Has oblidat la contrasenya?","de":"Passwort vergessen?","el":"Ξεχάσατε τον κωδικό;","fi":"Unohditko salasanan?","fr":"Mot de passe oublié ?","ga":"An ndearna tú dearmad ar do phasfhocal?","hi":"पासवर्ड भूल गए?","hr":"Zaboravili ste lozinku?","hu":"Elfelejtette jelszavát?","id":"Lupa kata sandi?","it":"Password dimenticata?","ja":"パスワードをお忘れですか？","ko":"비밀번호를 잊으셨나요?","nl":"Wachtwoord vergeten?","no":"Glemt passord?","pl":"Nie pamiętasz hasła?","pt":"Esqueceu a senha?","ro":"Ai uitat parola?","ru":"Забыли пароль?","sr":"Заборавили сте лозинку?","sv":"Glömt lösenord?","sw":"Umesahau nenosiri?","th":"ลืมรหัสผ่าน?","tr":"Şifrenizi mi unuttunuz?","vi":"Quên mật khẩu?","zh-Hans":"忘记密码？","zh-Hant":"忘記密碼？"},
        "sign_up": {"af":"Teken aan","ar":"التسجيل","ca":"Registrar-se","de":"Registrieren","el":"Εγγραφή","fi":"Rekisteröidy","fr":"S'inscrire","ga":"Cláraigh","hi":"साइन अप करें","hr":"Registriraj se","hu":"Regisztráció","id":"Daftar","it":"Registrati","ja":"登録","ko":"가입하기","nl":"Registreren","no":"Registrer deg","pl":"Zarejestruj się","pt":"Cadastrar","ro":"Înregistrare","ru":"Регистрация","sr":"Региструј се","sv":"Registrera dig","sw":"Jiandikishe","th":"สมัครสมาชิก","tr":"Kaydol","vi":"Đăng ký","zh-Hans":"注册","zh-Hant":"註冊"},
        "log_in": {"af":"Meld aan","ar":"تسجيل الدخول","ca":"Iniciar sessió","de":"Anmelden","el":"Σύνδεση","fi":"Kirjaudu sisään","fr":"Se connecter","ga":"Logáil isteach","hi":"लॉग इन करें","hr":"Prijavi se","hu":"Bejelentkezés","id":"Masuk","it":"Accedi","ja":"ログイン","ko":"로그인","nl":"Inloggen","no":"Logg inn","pl":"Zaloguj się","pt":"Entrar","ro":"Autentificare","ru":"Войти","sr":"Пријави се","sv":"Logga in","sw":"Ingia","th":"เข้าสู่ระบบ","tr":"Giriş Yap","vi":"Đăng nhập","zh-Hans":"登录","zh-Hant":"登入"},
        "log_out": {"af":"Meld af","ar":"تسجيل الخروج","ca":"Tancar sessió","de":"Abmelden","el":"Αποσύνδεση","fi":"Kirjaudu ulos","fr":"Se déconnecter","ga":"Logáil amach","hi":"लॉग आउट करें","hr":"Odjavi se","hu":"Kijelentkezés","id":"Keluar","it":"Esci","ja":"ログアウト","ko":"로그아웃","nl":"Uitloggen","no":"Logg ut","pl":"Wyloguj się","pt":"Sair","ro":"Deconectare","ru":"Выйти","sr":"Одјави се","sv":"Logga ut","sw":"Toka","th":"ออกจากระบบ","tr":"Çıkış Yap","vi":"Đăng xuất","zh-Hans":"退出登录","zh-Hant":"登出"},
        "create_account": {"af":"Skep rekening","ar":"إنشاء حساب","ca":"Crear compte","de":"Konto erstellen","el":"Δημιουργία λογαριασμού","fi":"Luo tili","fr":"Créer un compte","ga":"Cruthaigh cuntas","hi":"खाता बनाएं","hr":"Stvori račun","hu":"Fiók létrehozása","id":"Buat Akun","it":"Crea account","ja":"アカウント作成","ko":"계정 만들기","nl":"Account aanmaken","no":"Opprett konto","pl":"Utwórz konto","pt":"Criar conta","ro":"Creează cont","ru":"Создать аккаунт","sr":"Направи налог","sv":"Skapa konto","sw":"Unda akaunti","th":"สร้างบัญชี","tr":"Hesap Oluştur","vi":"Tạo tài khoản","zh-Hans":"创建账户","zh-Hant":"建立帳戶"},
        "verify_email": {"af":"Verifieer e-pos","ar":"تأكيد البريد الإلكتروني","ca":"Verificar correu","de":"E-Mail bestätigen","el":"Επαλήθευση email","fi":"Vahvista sähköposti","fr":"Vérifier l'e-mail","ga":"Fíoraigh ríomhphost","hi":"ईमेल सत्यापित करें","hr":"Potvrdi e-poštu","hu":"E-mail megerősítése","id":"Verifikasi Email","it":"Verifica email","ja":"メールを確認","ko":"이메일 인증","nl":"E-mail verifiëren","no":"Bekreft e-post","pl":"Zweryfikuj e-mail","pt":"Verificar e-mail","ro":"Verifică emailul","ru":"Подтвердить email","sr":"Потврди е-пошту","sv":"Verifiera e-post","sw":"Thibitisha barua pepe","th":"ยืนยันอีเมล","tr":"E-postayı Doğrula","vi":"Xác minh email","zh-Hans":"验证邮箱","zh-Hant":"驗證電子郵件"},
        "send_reset_link": {"af":"Stuur terugstelskakel","ar":"إرسال رابط إعادة التعيين","ca":"Enviar enllaç de restabliment","de":"Reset-Link senden","el":"Αποστολή συνδέσμου επαναφοράς","fi":"Lähetä palautuslinkki","fr":"Envoyer le lien de réinitialisation","ga":"Seol nasc athshocraithe","hi":"रीसेट लिंक भेजें","hr":"Pošalji poveznicu za resetiranje","hu":"Visszaállítási link küldése","id":"Kirim Tautan Reset","it":"Invia link di ripristino","ja":"リセットリンクを送信","ko":"재설정 링크 보내기","nl":"Resetlink versturen","no":"Send tilbakestillingslenke","pl":"Wyślij link resetowania","pt":"Enviar link de redefinição","ro":"Trimite linkul de resetare","ru":"Отправить ссылку для сброса","sr":"Пошаљи линк за ресетовање","sv":"Skicka återställningslänk","sw":"Tuma kiungo cha kuweka upya","th":"ส่งลิงก์รีเซ็ต","tr":"Sıfırlama Bağlantısı Gönder","vi":"Gửi liên kết đặt lại","zh-Hans":"发送重置链接","zh-Hant":"傳送重設連結"},
        "back_to_login": {"af":"Terug na aanmelding","ar":"العودة إلى تسجيل الدخول","ca":"Tornar a l'inici de sessió","de":"Zurück zur Anmeldung","el":"Επιστροφή στη σύνδεση","fi":"Takaisin kirjautumiseen","fr":"Retour à la connexion","ga":"Ar ais go dtí logáil isteach","hi":"लॉगिन पर वापस जाएं","hr":"Natrag na prijavu","hu":"Vissza a bejelentkezéshez","id":"Kembali ke login","it":"Torna al login","ja":"ログインに戻る","ko":"로그인으로 돌아가기","nl":"Terug naar inloggen","no":"Tilbake til innlogging","pl":"Powrót do logowania","pt":"Voltar ao login","ro":"Înapoi la autentificare","ru":"Вернуться ко входу","sr":"Назад на пријаву","sv":"Tillbaka till inloggning","sw":"Rudi kwenye kuingia","th":"กลับไปเข้าสู่ระบบ","tr":"Girişe geri dön","vi":"Quay lại đăng nhập","zh-Hans":"返回登录","zh-Hant":"返回登入"},
        "continue": {"af":"Gaan voort","ar":"متابعة","ca":"Continuar","de":"Weiter","el":"Συνέχεια","fi":"Jatka","fr":"Continuer","ga":"Lean ar aghaidh","hi":"जारी रखें","hr":"Nastavi","hu":"Folytatás","id":"Lanjutkan","it":"Continua","ja":"続ける","ko":"계속","nl":"Doorgaan","no":"Fortsett","pl":"Kontynuuj","pt":"Continuar","ro":"Continuă","ru":"Продолжить","sr":"Настави","sv":"Fortsätt","sw":"Endelea","th":"ดำเนินการต่อ","tr":"Devam Et","vi":"Tiếp tục","zh-Hans":"继续","zh-Hant":"繼續"},
        "try_again": {"af":"Probeer weer","ar":"حاول مرة أخرى","ca":"Tornar a provar","de":"Erneut versuchen","el":"Δοκιμάστε ξανά","fi":"Yritä uudelleen","fr":"Réessayer","ga":"Bain triail eile as","hi":"पुनः प्रयास करें","hr":"Pokušaj ponovno","hu":"Próbálja újra","id":"Coba Lagi","it":"Riprova","ja":"もう一度試す","ko":"다시 시도","nl":"Opnieuw proberen","no":"Prøv igjen","pl":"Spróbuj ponownie","pt":"Tentar novamente","ro":"Încearcă din nou","ru":"Попробовать снова","sr":"Покушај поново","sv":"Försök igen","sw":"Jaribu tena","th":"ลองอีกครั้ง","tr":"Tekrar Dene","vi":"Thử lại","zh-Hans":"重试","zh-Hant":"再試一次"},
        "start_watching": {"af":"Begin kyk","ar":"بدء المشاهدة","ca":"Començar a veure","de":"Anschauen starten","el":"Έναρξη παρακολούθησης","fi":"Aloita katselu","fr":"Commencer à regarder","ga":"Tosaigh ag féachaint","hi":"देखना शुरू करें","hr":"Počni gledati","hu":"Nézés indítása","id":"Mulai Menonton","it":"Inizia a guardare","ja":"視聴を開始","ko":"시청 시작","nl":"Beginnen met kijken","no":"Begynn å se","pl":"Zacznij oglądać","pt":"Começar a assistir","ro":"Începe vizionarea","ru":"Начать просмотр","sr":"Почни да гледаш","sv":"Börja titta","sw":"Anza kutazama","th":"เริ่มรับชม","tr":"İzlemeye Başla","vi":"Bắt đầu xem","zh-Hans":"开始观看","zh-Hant":"開始觀看"},
    },
    "msg": {
        "log_in_to_continue": {"af":"Meld aan om aan te hou leer.","ar":"سجل الدخول لمواصلة التعلم.","ca":"Inicia sessió per continuar aprenent.","de":"Melden Sie sich an, um weiter zu lernen.","el":"Συνδεθείτε για να συνεχίσετε τη μάθηση.","fi":"Kirjaudu sisään jatkaaksesi oppimista.","fr":"Connectez-vous pour continuer à apprendre.","ga":"Logáil isteach chun leanúint ag foghlaim.","hi":"सीखना जारी रखने के लिए लॉग इन करें।","hr":"Prijavite se za nastavak učenja.","hu":"Jelentkezzen be a tanulás folytatásához.","id":"Masuk untuk melanjutkan belajar.","it":"Accedi per continuare ad imparare.","ja":"ログインして学習を続けましょう。","ko":"로그인하여 학습을 계속하세요.","nl":"Log in om verder te leren.","no":"Logg inn for å fortsette å lære.","pl":"Zaloguj się, aby kontynuować naukę.","pt":"Faça login para continuar aprendendo.","ro":"Autentificați-vă pentru a continua învățarea.","ru":"Войдите, чтобы продолжить обучение.","sr":"Пријавите се да бисте наставили са учењем.","sv":"Logga in för att fortsätta lära dig.","sw":"Ingia ili kuendelea kujifunza.","th":"เข้าสู่ระบบเพื่อเรียนรู้ต่อ","tr":"Öğrenmeye devam etmek için giriş yapın.","vi":"Đăng nhập để tiếp tục học.","zh-Hans":"登录以继续学习。","zh-Hant":"登入以繼續學習。"},
        "dont_have_account": {"af":"Het jy nie 'n rekening nie?","ar":"ليس لديك حساب؟","ca":"No tens un compte?","de":"Sie haben noch kein Konto?","el":"Δεν έχετε λογαριασμό;","fi":"Eikö sinulla ole tiliä?","fr":"Vous n'avez pas de compte ?","ga":"Níl cuntas agat?","hi":"खाता नहीं है?","hr":"Nemate račun?","hu":"Nincs még fiókja?","id":"Belum punya akun?","it":"Non hai un account?","ja":"アカウントをお持ちではありませんか？","ko":"계정이 없으신가요?","nl":"Nog geen account?","no":"Har du ikke en konto?","pl":"Nie masz konta?","pt":"Não tem uma conta?","ro":"Nu aveți un cont?","ru":"Нет аккаунта?","sr":"Немате налог?","sv":"Har du inget konto?","sw":"Huna akaunti?","th":"ยังไม่มีบัญชี?","tr":"Hesabınız yok mu?","vi":"Chưa có tài khoản?","zh-Hans":"还没有账户？","zh-Hant":"還沒有帳戶？"},
        "start_learning": {"af":"Begin tale leer deur outentieke video-inhoud.","ar":"ابدأ في تعلم اللغات من خلال محتوى فيديو أصلي.","ca":"Comença a aprendre idiomes amb contingut de vídeo autèntic.","de":"Lernen Sie Sprachen mit authentischen Videoinhalten.","el":"Ξεκινήστε να μαθαίνετε γλώσσες μέσω αυθεντικού περιεχομένου βίντεο.","fi":"Aloita kielten oppiminen autenttisen videosisällön avulla.","fr":"Commencez à apprendre des langues avec du contenu vidéo authentique.","ga":"Tosaigh ag foghlaim teangacha trí ábhar físe barántúil.","hi":"प्रामाणिक वीडियो सामग्री के माध्यम से भाषाएँ सीखना शुरू करें।","hr":"Počnite učiti jezike kroz autentični video sadržaj.","hu":"Kezdjen el nyelveket tanulni autentikus videótartalmakon keresztül.","id":"Mulai belajar bahasa melalui konten video otentik.","it":"Inizia a imparare le lingue con contenuti video autentici.","ja":"本格的な動画コンテンツで言語を学び始めましょう。","ko":"실제 비디오 콘텐츠로 언어 학습을 시작하세요.","nl":"Begin met talen leren via authentieke videocontent.","no":"Begynn å lære språk gjennom autentisk videoinnhold.","pl":"Zacznij uczyć się języków poprzez autentyczne treści wideo.","pt":"Comece a aprender idiomas com conteúdo de vídeo autêntico.","ro":"Începeți să învățați limbi prin conținut video autentic.","ru":"Начните изучать языки с помощью аутентичного видеоконтента.","sr":"Започните учење језика кроз аутентични видео садржај.","sv":"Börja lära dig språk genom autentiskt videoinnehåll.","sw":"Anza kujifunza lugha kupitia maudhui halisi ya video.","th":"เริ่มเรียนภาษาผ่านเนื้อหาวิดีโอจริง","tr":"Otantik video içerikleriyle dil öğrenmeye başlayın.","vi":"Bắt đầu học ngôn ngữ qua nội dung video thực tế.","zh-Hans":"通过真实视频内容开始学习语言。","zh-Hant":"透過真實影片內容開始學習語言。"},
        "creating_account": {"af":"Skep rekening...","ar":"جارٍ إنشاء الحساب...","ca":"Creant compte...","de":"Konto wird erstellt...","el":"Δημιουργία λογαριασμού...","fi":"Luodaan tiliä...","fr":"Création du compte...","ga":"Cuntas á chruthú...","hi":"खाता बनाया जा रहा है...","hr":"Stvaranje računa...","hu":"Fiók létrehozása...","id":"Membuat akun...","it":"Creazione account...","ja":"アカウントを作成中...","ko":"계정 생성 중...","nl":"Account aanmaken...","no":"Oppretter konto...","pl":"Tworzenie konta...","pt":"Criando conta...","ro":"Se creează contul...","ru":"Создание аккаунта...","sr":"Прављење налога...","sv":"Skapar konto...","sw":"Inaunda akaunti...","th":"กำลังสร้างบัญชี...","tr":"Hesap oluşturuluyor...","vi":"Đang tạo tài khoản...","zh-Hans":"正在创建账户...","zh-Hant":"正在建立帳戶..."},
        "logging_in": {"af":"Meld aan...","ar":"جارٍ تسجيل الدخول...","ca":"Iniciant sessió...","de":"Anmeldung läuft...","el":"Σύνδεση...","fi":"Kirjaudutaan...","fr":"Connexion en cours...","ga":"Ag logáil isteach...","hi":"लॉग इन हो रहा है...","hr":"Prijava u tijeku...","hu":"Bejelentkezés...","id":"Sedang masuk...","it":"Accesso in corso...","ja":"ログイン中...","ko":"로그인 중...","nl":"Inloggen...","no":"Logger inn...","pl":"Logowanie...","pt":"Entrando...","ro":"Se autentifică...","ru":"Вход в систему...","sr":"Пријављивање...","sv":"Loggar in...","sw":"Inaingia...","th":"กำลังเข้าสู่ระบบ...","tr":"Giriş yapılıyor...","vi":"Đang đăng nhập...","zh-Hans":"正在登录...","zh-Hant":"正在登入..."},
        "verification_code_sent": {"af":"Ons het 'n verifikasiekode na {email} gestuur. Voer dit hieronder in.","ar":"أرسلنا رمز التحقق إلى {email}. أدخله أدناه.","ca":"Hem enviat un codi de verificació a {email}. Introdueix-lo a continuació.","de":"Wir haben einen Bestätigungscode an {email} gesendet. Geben Sie ihn unten ein.","el":"Στείλαμε έναν κωδικό επαλήθευσης στο {email}. Εισάγετέ τον παρακάτω.","fi":"Lähetimme vahvistuskoodin osoitteeseen {email}. Syötä se alle.","fr":"Nous avons envoyé un code de vérification à {email}. Saisissez-le ci-dessous.","ga":"Sheolamar cód fíorúcháin chuig {email}. Iontráil thíos é.","hi":"हमने {email} पर एक सत्यापन कोड भेजा है। इसे नीचे दर्ज करें।","hr":"Poslali smo verifikacijski kod na {email}. Unesite ga u nastavku.","hu":"Küldtünk egy megerősítő kódot a következő címre: {email}. Írja be alább.","id":"Kami telah mengirim kode verifikasi ke {email}. Masukkan di bawah ini.","it":"Abbiamo inviato un codice di verifica a {email}. Inseriscilo qui sotto.","ja":"{email} に確認コードを送信しました。以下に入力してください。","ko":"{email}로 인증 코드를 보냈습니다. 아래에 입력하세요.","nl":"We hebben een verificatiecode gestuurd naar {email}. Voer deze hieronder in.","no":"Vi har sendt en bekreftelseskode til {email}. Skriv den inn nedenfor.","pl":"Wysłaliśmy kod weryfikacyjny na {email}. Wprowadź go poniżej.","pt":"Enviamos um código de verificação para {email}. Insira-o abaixo.","ro":"Am trimis un cod de verificare la {email}. Introduceți-l mai jos.","ru":"Мы отправили код подтверждения на {email}. Введите его ниже.","sr":"Послали смо верификациони код на {email}. Унесите га испод.","sv":"Vi har skickat en verifieringskod till {email}. Ange den nedan.","sw":"Tumetuma nambari ya uthibitishaji kwa {email}. Iweke hapa chini.","th":"เราได้ส่งรหัสยืนยันไปยัง {email} กรุณากรอกด้านล่าง","tr":"{email} adresine bir doğrulama kodu gönderdik. Aşağıya girin.","vi":"Chúng tôi đã gửi mã xác minh đến {email}. Nhập mã bên dưới.","zh-Hans":"我们已发送验证码到 {email}。请在下方输入。","zh-Hant":"我們已傳送驗證碼到 {email}。請在下方輸入。"},
        "enter_email_for_reset": {"af":"Voer jou e-posadres in en ons sal vir jou 'n terugstelskakel stuur.","ar":"أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.","ca":"Introdueix el teu correu electrònic i t'enviarem un enllaç de restabliment.","de":"Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Reset-Link.","el":"Εισάγετε το email σας και θα σας στείλουμε έναν σύνδεσμο επαναφοράς.","fi":"Syötä sähköpostiosoitteesi, niin lähetämme sinulle palautuslinkin.","fr":"Entrez votre e-mail et nous vous enverrons un lien de réinitialisation.","ga":"Iontráil do ríomhphost agus seolfaimid nasc athshocraithe chugat.","hi":"अपना ईमेल दर्ज करें और हम आपको एक रीसेट लिंक भेजेंगे।","hr":"Unesite svoju e-poštu i poslat ćemo vam poveznicu za resetiranje.","hu":"Adja meg az e-mail címét, és küldünk egy visszaállítási linket.","id":"Masukkan email Anda dan kami akan mengirimkan tautan reset.","it":"Inserisci la tua email e ti invieremo un link di ripristino.","ja":"メールアドレスを入力してください。リセットリンクをお送りします。","ko":"이메일을 입력하시면 재설정 링크를 보내드립니다.","nl":"Voer uw e-mailadres in en we sturen u een resetlink.","no":"Skriv inn e-posten din så sender vi deg en tilbakestillingslenke.","pl":"Wprowadź swój e-mail, a wyślemy Ci link resetowania.","pt":"Digite seu e-mail e enviaremos um link de redefinição.","ro":"Introduceți emailul dvs. și vă vom trimite un link de resetare.","ru":"Введите ваш email, и мы отправим ссылку для сброса.","sr":"Унесите своју е-пошту и послаћемо вам линк за ресетовање.","sv":"Ange din e-postadress så skickar vi en återställningslänk.","sw":"Weka barua pepe yako na tutakutumia kiungo cha kuweka upya.","th":"กรอกอีเมลของคุณแล้วเราจะส่งลิงก์รีเซ็ตให้","tr":"E-postanızı girin, size bir sıfırlama bağlantısı gönderelim.","vi":"Nhập email của bạn và chúng tôi sẽ gửi liên kết đặt lại.","zh-Hans":"输入您的邮箱，我们将发送重置链接。","zh-Hant":"輸入您的電子郵件，我們將傳送重設連結。"},
        "choose_languages": {"af":"Kies jou tale om te begin","ar":"اختر لغاتك للبدء","ca":"Tria els teus idiomes per començar","de":"Wählen Sie Ihre Sprachen zum Starten","el":"Επιλέξτε τις γλώσσες σας για να ξεκινήσετε","fi":"Valitse kielesi aloittaaksesi","fr":"Choisissez vos langues pour commencer","ga":"Roghnaigh do theangacha chun tosú","hi":"शुरू करने के लिए अपनी भाषाएँ चुनें","hr":"Odaberite svoje jezike za početak","hu":"Válassza ki a nyelveit a kezdéshez","id":"Pilih bahasa Anda untuk memulai","it":"Scegli le tue lingue per iniziare","ja":"学習する言語を選択してください","ko":"시작할 언어를 선택하세요","nl":"Kies uw talen om te beginnen","no":"Velg språkene dine for å komme i gang","pl":"Wybierz swoje języki, aby rozpocząć","pt":"Escolha seus idiomas para começar","ro":"Alegeți limbile dvs. pentru a începe","ru":"Выберите языки, чтобы начать","sr":"Изаберите своје језике за почетак","sv":"Välj dina språk för att komma igång","sw":"Chagua lugha zako ili kuanza","th":"เลือกภาษาของคุณเพื่อเริ่มต้น","tr":"Başlamak için dillerinizi seçin","vi":"Chọn ngôn ngữ của bạn để bắt đầu","zh-Hans":"选择您的语言以开始","zh-Hant":"選擇您的語言以開始"},
        "no_videos_found": {"af":"Geen video's gevind nie. Probeer 'n ander vlak of kom later terug.","ar":"لم يتم العثور على فيديوهات. جرب مستوى آخر أو عد لاحقًا.","ca":"No s'han trobat vídeos. Prova un altre nivell o torna més tard.","de":"Keine Videos gefunden. Versuchen Sie ein anderes Niveau oder schauen Sie später wieder vorbei.","el":"Δεν βρέθηκαν βίντεο. Δοκιμάστε άλλο επίπεδο ή ελέγξτε αργότερα.","fi":"Videoita ei löytynyt. Kokeile toista tasoa tai palaa myöhemmin.","fr":"Aucune vidéo trouvée. Essayez un autre niveau ou revenez plus tard.","ga":"Níor aimsíodh aon fhíseáin. Bain triail as leibhéal eile nó seiceáil arís níos déanaí.","hi":"कोई वीडियो नहीं मिला। कोई अन्य स्तर आज़माएं या बाद में पुनः जांचें।","hr":"Nisu pronađeni videozapisi. Pokušajte drugu razinu ili provjerite kasnije.","hu":"Nem találhatók videók. Próbáljon másik szintet, vagy nézzen vissza később.","id":"Tidak ada video ditemukan. Coba level lain atau periksa kembali nanti.","it":"Nessun video trovato. Prova un altro livello o torna più tardi.","ja":"動画が見つかりません。別のレベルを試すか、後でもう一度確認してください。","ko":"비디오를 찾을 수 없습니다. 다른 레벨을 시도하거나 나중에 다시 확인하세요.","nl":"Geen video's gevonden. Probeer een ander niveau of kom later terug.","no":"Ingen videoer funnet. Prøv et annet nivå eller kom tilbake senere.","pl":"Nie znaleziono filmów. Wypróbuj inny poziom lub sprawdź później.","pt":"Nenhum vídeo encontrado. Tente outro nível ou volte mais tarde.","ro":"Nu s-au găsit videoclipuri. Încercați un alt nivel sau reveniți mai târziu.","ru":"Видео не найдены. Попробуйте другой уровень или зайдите позже.","sr":"Нису пронађени видео снимци. Покушајте други ниво или проверите касније.","sv":"Inga videor hittades. Testa en annan nivå eller kom tillbaka senare.","sw":"Hakuna video zilizopatikana. Jaribu kiwango kingine au angalia tena baadaye.","th":"ไม่พบวิดีโอ ลองเปลี่ยนระดับหรือกลับมาใหม่ทีหลัง","tr":"Video bulunamadı. Farklı bir seviye deneyin veya daha sonra tekrar kontrol edin.","vi":"Không tìm thấy video. Hãy thử cấp độ khác hoặc kiểm tra lại sau.","zh-Hans":"未找到视频。请尝试其他级别或稍后再来。","zh-Hant":"未找到影片。請嘗試其他級別或稍後再來。"},
        "end_of_list": {"af":"Jy het die einde van die lys bereik.","ar":"لقد وصلت إلى نهاية القائمة.","ca":"Has arribat al final de la llista.","de":"Sie haben das Ende der Liste erreicht.","el":"Φτάσατε στο τέλος της λίστας.","fi":"Olet saavuttanut listan lopun.","fr":"Vous avez atteint la fin de la liste.","ga":"Tá deireadh an liosta bainte amach agat.","hi":"आप सूची के अंत तक पहुँच गए हैं।","hr":"Došli ste do kraja popisa.","hu":"Elérte a lista végét.","id":"Anda telah mencapai akhir daftar.","it":"Hai raggiunto la fine della lista.","ja":"リストの最後に達しました。","ko":"목록의 끝에 도달했습니다.","nl":"U hebt het einde van de lijst bereikt.","no":"Du har nådd slutten av listen.","pl":"Osiągnąłeś koniec listy.","pt":"Você chegou ao fim da lista.","ro":"Ați ajuns la sfârșitul listei.","ru":"Вы достигли конца списка.","sr":"Дошли сте до краја листе.","sv":"Du har nått slutet av listan.","sw":"Umefika mwisho wa orodha.","th":"คุณมาถึงจุดสิ้นสุดของรายการแล้ว","tr":"Listenin sonuna ulaştınız.","vi":"Bạn đã đến cuối danh sách.","zh-Hans":"您已到达列表末尾。","zh-Hant":"您已到達列表末尾。"},
        "subtitles_not_available": {"af":"Onderskrifte is nog nie vir hierdie video beskikbaar nie.","ar":"الترجمات غير متاحة لهذا الفيديو بعد.","ca":"Els subtítols encara no estan disponibles per a aquest vídeo.","de":"Untertitel sind für dieses Video noch nicht verfügbar.","el":"Οι υπότιτλοι δεν είναι ακόμη διαθέσιμοι για αυτό το βίντεο.","fi":"Tekstitykset eivät ole vielä saatavilla tälle videolle.","fr":"Les sous-titres ne sont pas encore disponibles pour cette vidéo.","ga":"Níl fotheidil ar fáil don fhíseán seo go fóill.","hi":"इस वीडियो के लिए उपशीर्षक अभी उपलब्ध नहीं हैं।","hr":"Titlovi još nisu dostupni za ovaj videozapis.","hu":"A felirat még nem érhető el ehhez a videóhoz.","id":"Subtitle belum tersedia untuk video ini.","it":"I sottotitoli non sono ancora disponibili per questo video.","ja":"この動画の字幕はまだ利用できません。","ko":"이 비디오의 자막은 아직 사용할 수 없습니다.","nl":"Ondertiteling is nog niet beschikbaar voor deze video.","no":"Undertekster er ikke tilgjengelig for denne videoen ennå.","pl":"Napisy nie są jeszcze dostępne dla tego filmu.","pt":"As legendas ainda não estão disponíveis para este vídeo.","ro":"Subtitrările nu sunt încă disponibile pentru acest videoclip.","ru":"Субтитры для этого видео пока недоступны.","sr":"Титлови још нису доступни за овај видео.","sv":"Undertexter är inte tillgängliga för denna video än.","sw":"Manukuu bado hayapatikani kwa video hii.","th":"คำบรรยายยังไม่พร้อมสำหรับวิดีโอนี้","tr":"Bu video için altyazılar henüz mevcut değil.","vi":"Phụ đề chưa có sẵn cho video này.","zh-Hans":"此视频的字幕尚不可用。","zh-Hant":"此影片的字幕尚不可用。"},
        "video_unavailable": {"af":"Hierdie video kon nie gelaai word nie. Dit is moontlik verwyder of privaat gemaak.","ar":"تعذر تحميل هذا الفيديو. ربما تم حذفه أو جعله خاصًا.","ca":"Aquest vídeo no s'ha pogut carregar. Pot haver estat eliminat o fet privat.","de":"Dieses Video konnte nicht geladen werden. Es wurde möglicherweise entfernt oder auf privat gesetzt.","el":"Αυτό το βίντεο δεν μπόρεσε να φορτωθεί. Μπορεί να έχει αφαιρεθεί ή να έχει γίνει ιδιωτικό.","fi":"Tätä videota ei voitu ladata. Se on saatettu poistaa tai asettaa yksityiseksi.","fr":"Cette vidéo n'a pas pu être chargée. Elle a peut-être été supprimée ou rendue privée.","ga":"Níorbh fhéidir an físeán seo a lódáil. Seans gur baineadh é nó gur rinneadh príobháideach é.","hi":"यह वीडियो लोड नहीं किया जा सका। हो सकता है इसे हटा दिया गया हो या निजी बना दिया गया हो।","hr":"Ovaj se videozapis nije mogao učitati. Možda je uklonjen ili postavljen kao privatan.","hu":"Ezt a videót nem sikerült betölteni. Lehet, hogy eltávolították vagy priváttá tették.","id":"Video ini tidak dapat dimuat. Mungkin telah dihapus atau dibuat pribadi.","it":"Questo video non può essere caricato. Potrebbe essere stato rimosso o reso privato.","ja":"この動画を読み込めませんでした。削除されたか非公開になった可能性があります。","ko":"이 비디오를 로드할 수 없습니다. 삭제되었거나 비공개로 설정되었을 수 있습니다.","nl":"Deze video kon niet worden geladen. Mogelijk is deze verwijderd of privé gemaakt.","no":"Denne videoen kunne ikke lastes inn. Den kan ha blitt fjernet eller gjort privat.","pl":"Ten film nie mógł zostać załadowany. Mógł zostać usunięty lub ustawiony jako prywatny.","pt":"Este vídeo não pôde ser carregado. Pode ter sido removido ou tornado privado.","ro":"Acest videoclip nu a putut fi încărcat. Este posibil să fi fost eliminat sau făcut privat.","ru":"Это видео не может быть загружено. Возможно, оно было удалено или сделано приватным.","sr":"Овај видео није могао да се учита. Можда је уклоњен или постављен као приватан.","sv":"Denna video kunde inte laddas. Den kan ha tagits bort eller gjorts privat.","sw":"Video hii haikuweza kupakiwa. Huenda imeondolewa au imefanywa kuwa ya faragha.","th":"ไม่สามารถโหลดวิดีโอนี้ อาจถูกลบหรือตั้งเป็นส่วนตัว","tr":"Bu video yüklenemedi. Kaldırılmış veya gizli yapılmış olabilir.","vi":"Không thể tải video này. Có thể video đã bị xóa hoặc đặt ở chế độ riêng tư.","zh-Hans":"无法加载此视频。可能已被删除或设为私密。","zh-Hant":"無法載入此影片。可能已被刪除或設為私密。"},
    },
    "placeholder": {
        "password_min": {"af":"Min. 8 karakters","ar":"الحد الأدنى 8 أحرف","ca":"Mín. 8 caràcters","de":"Mind. 8 Zeichen","el":"Ελάχ. 8 χαρακτήρες","fi":"Väh. 8 merkkiä","fr":"Min. 8 caractères","ga":"Íosmhéid 8 gcarachtar","hi":"न्यूनतम 8 अक्षर","hr":"Min. 8 znakova","hu":"Min. 8 karakter","id":"Min. 8 karakter","it":"Min. 8 caratteri","ja":"最低8文字","ko":"최소 8자","nl":"Min. 8 tekens","no":"Min. 8 tegn","pl":"Min. 8 znaków","pt":"Mín. 8 caracteres","ro":"Min. 8 caractere","ru":"Мин. 8 символов","sr":"Мин. 8 карактера","sv":"Minst 8 tecken","sw":"Angalau herufi 8","th":"ขั้นต่ำ 8 ตัวอักษร","tr":"En az 8 karakter","vi":"Tối thiểu 8 ký tự","zh-Hans":"最少 8 个字符","zh-Hant":"最少 8 個字元"},
        "verification_code": {"af":"Verifikasiekode","ar":"رمز التحقق","ca":"Codi de verificació","de":"Bestätigungscode","el":"Κωδικός επαλήθευσης","fi":"Vahvistuskoodi","fr":"Code de vérification","ga":"Cód fíorúcháin","hi":"सत्यापन कोड","hr":"Verifikacijski kod","hu":"Megerősítő kód","id":"Kode verifikasi","it":"Codice di verifica","ja":"確認コード","ko":"인증 코드","nl":"Verificatiecode","no":"Bekreftelseskode","pl":"Kod weryfikacyjny","pt":"Código de verificação","ro":"Cod de verificare","ru":"Код подтверждения","sr":"Верификациони код","sv":"Verifieringskod","sw":"Nambari ya uthibitishaji","th":"รหัสยืนยัน","tr":"Doğrulama kodu","vi":"Mã xác minh","zh-Hans":"验证码","zh-Hant":"驗證碼"},
        "search_languages": {"af":"Soek tale...","ar":"البحث عن اللغات...","ca":"Cercar idiomes...","de":"Sprachen suchen...","el":"Αναζήτηση γλωσσών...","fi":"Etsi kieliä...","fr":"Rechercher des langues...","ga":"Cuardaigh teangacha...","hi":"भाषाएँ खोजें...","hr":"Pretraži jezike...","hu":"Nyelvek keresése...","id":"Cari bahasa...","it":"Cerca lingue...","ja":"言語を検索...","ko":"언어 검색...","nl":"Talen zoeken...","no":"Søk etter språk...","pl":"Szukaj języków...","pt":"Buscar idiomas...","ro":"Căutați limbi...","ru":"Поиск языков...","sr":"Претражи језике...","sv":"Sök språk...","sw":"Tafuta lugha...","th":"ค้นหาภาษา...","tr":"Dil ara...","vi":"Tìm kiếm ngôn ngữ...","zh-Hans":"搜索语言...","zh-Hant":"搜尋語言..."},
    },
    "button": {
        "email_support": {"af":"E-posondersteuning","ar":"الدعم عبر البريد الإلكتروني","ca":"Assistència per correu","de":"E-Mail-Support","el":"Υποστήριξη μέσω email","fi":"Sähköpostituki","fr":"Assistance par e-mail","ga":"Tacaíocht ríomhphoist","hi":"ईमेल सहायता","hr":"Podrška e-poštom","hu":"E-mail támogatás","id":"Dukungan Email","it":"Supporto email","ja":"メールサポート","ko":"이메일 지원","nl":"E-mailondersteuning","no":"E-poststøtte","pl":"Wsparcie e-mail","pt":"Suporte por e-mail","ro":"Suport prin email","ru":"Поддержка по email","sr":"Подршка путем е-поште","sv":"E-postsupport","sw":"Usaidizi wa barua pepe","th":"สนับสนุนทางอีเมล","tr":"E-posta Desteği","vi":"Hỗ trợ qua email","zh-Hans":"邮件支持","zh-Hant":"電子郵件支援"},
        "processing": {"af":"Verwerk...","ar":"جارٍ المعالجة...","ca":"Processant...","de":"Wird verarbeitet...","el":"Επεξεργασία...","fi":"Käsitellään...","fr":"Traitement en cours...","ga":"Á phróiseáil...","hi":"प्रसंस्करण हो रहा है...","hr":"Obrada...","hu":"Feldolgozás...","id":"Memproses...","it":"Elaborazione...","ja":"処理中...","ko":"처리 중...","nl":"Verwerken...","no":"Behandler...","pl":"Przetwarzanie...","pt":"Processando...","ro":"Se procesează...","ru":"Обработка...","sr":"Обрада...","sv":"Bearbetar...","sw":"Inashughulikia...","th":"กำลังดำเนินการ...","tr":"İşleniyor...","vi":"Đang xử lý...","zh-Hans":"处理中...","zh-Hant":"處理中..."},
        "purchase": {"af":"Koop","ar":"شراء","ca":"Comprar","de":"Kaufen","el":"Αγορά","fi":"Osta","fr":"Acheter","ga":"Ceannaigh","hi":"खरीदें","hr":"Kupi","hu":"Vásárlás","id":"Beli","it":"Acquista","ja":"購入","ko":"구매","nl":"Kopen","no":"Kjøp","pl":"Kup","pt":"Comprar","ro":"Cumpără","ru":"Купить","sr":"Купи","sv":"Köp","sw":"Nunua","th":"ซื้อ","tr":"Satın Al","vi":"Mua","zh-Hans":"购买","zh-Hant":"購買"},
        "switch_to_lifetime": {"af":"Skakel oor na lewenslange plan","ar":"التبديل إلى الخطة مدى الحياة","ca":"Canviar al pla vitalici","de":"Zum Lifetime-Plan wechseln","el":"Μετάβαση σε ισόβιο πρόγραμμα","fi":"Vaihda elinikäiseen sopimukseen","fr":"Passer au plan à vie","ga":"Athraigh go dtí plean saoil","hi":"आजीवन योजना पर स्विच करें","hr":"Prebaci na doživotni plan","hu":"Váltás élettartam csomagra","id":"Beralih ke Paket Seumur Hidup","it":"Passa al piano a vita","ja":"ライフタイムプランに切り替え","ko":"평생 플랜으로 전환","nl":"Overstappen naar levenslang abonnement","no":"Bytt til livstidsplan","pl":"Przełącz na plan dożywotni","pt":"Mudar para plano vitalício","ro":"Treci la planul pe viață","ru":"Перейти на пожизненный план","sr":"Пребаци на доживотни план","sv":"Byt till livstidsplan","sw":"Badilisha hadi mpango wa maisha","th":"เปลี่ยนเป็นแผนตลอดชีพ","tr":"Ömür Boyu Plana Geç","vi":"Chuyển sang gói trọn đời","zh-Hans":"切换至终身计划","zh-Hant":"切換至終身計劃"},
    },
    "email": {
        "body": {"af":"Beskryf asseblief jou probleem of vraag.","ar":"يرجى وصف مشكلتك أو سؤالك.","ca":"Descriu el teu problema o consulta.","de":"Bitte beschreiben Sie Ihr Problem oder Ihre Frage.","el":"Περιγράψτε το πρόβλημα ή την ερώτησή σας.","fi":"Kuvaile ongelmasi tai kysymyksesi.","fr":"Veuillez décrire votre problème ou question.","ga":"Cuir síos ar d'fhadhb nó ar do cheist.","hi":"कृपया अपनी समस्या या प्रश्न का वर्णन करें।","hr":"Opišite svoj problem ili pitanje.","hu":"Kérjük, írja le a problémáját vagy kérdését.","id":"Silakan jelaskan masalah atau pertanyaan Anda.","it":"Descrivi il tuo problema o domanda.","ja":"問題や質問の内容を記入してください。","ko":"문제나 질문을 설명해 주세요.","nl":"Beschrijf uw probleem of vraag.","no":"Beskriv problemet eller spørsmålet ditt.","pl":"Opisz swój problem lub pytanie.","pt":"Descreva seu problema ou dúvida.","ro":"Vă rugăm să descrieți problema sau întrebarea dvs.","ru":"Опишите вашу проблему или вопрос.","sr":"Опишите свој проблем или питање.","sv":"Beskriv ditt problem eller din fråga.","sw":"Tafadhali elezea tatizo lako au swali lako.","th":"กรุณาอธิบายปัญหาหรือคำถามของคุณ","tr":"Lütfen sorununuzu veya sorunuzu açıklayın.","vi":"Vui lòng mô tả vấn đề hoặc câu hỏi của bạn.","zh-Hans":"请描述您的问题或疑问。","zh-Hant":"請描述您的問題或疑問。"},
        "subject": {"af":"Ondersteuningsversoek","ar":"طلب دعم","ca":"Sol·licitud d'assistència","de":"Support-Anfrage","el":"Αίτημα υποστήριξης","fi":"Tukipyyntö","fr":"Demande d'assistance","ga":"Iarratas tacaíochta","hi":"सहायता अनुरोध","hr":"Zahtjev za podršku","hu":"Támogatási kérelem","id":"Permintaan Dukungan","it":"Richiesta di supporto","ja":"サポートリクエスト","ko":"지원 요청","nl":"Ondersteuningsverzoek","no":"Støtteforespørsel","pl":"Prośba o wsparcie","pt":"Solicitação de suporte","ro":"Cerere de asistență","ru":"Запрос в поддержку","sr":"Захтев за подршку","sv":"Supportförfrågan","sw":"Ombi la usaidizi","th":"คำขอรับการสนับสนุน","tr":"Destek Talebi","vi":"Yêu cầu hỗ trợ","zh-Hans":"支持请求","zh-Hant":"支援請求"},
    },
    "error": {
        "occurred": {"af":"'n Fout het voorgekom","ar":"حدث خطأ","ca":"S'ha produït un error","de":"Ein Fehler ist aufgetreten","el":"Παρουσιάστηκε σφάλμα","fi":"Tapahtui virhe","fr":"Une erreur est survenue","ga":"Tharla earráid","hi":"एक त्रुटि हुई","hr":"Došlo je do pogreške","hu":"Hiba történt","id":"Terjadi kesalahan","it":"Si è verificato un errore","ja":"エラーが発生しました","ko":"오류가 발생했습니다","nl":"Er is een fout opgetreden","no":"Det oppstod en feil","pl":"Wystąpił błąd","pt":"Ocorreu um erro","ro":"A apărut o eroare","ru":"Произошла ошибка","sr":"Дошло је до грешке","sv":"Ett fel inträffade","sw":"Hitilafu imetokea","th":"เกิดข้อผิดพลาด","tr":"Bir hata oluştu","vi":"Đã xảy ra lỗi","zh-Hans":"发生错误","zh-Hant":"發生錯誤"},
    },
    "subtitle": {
        "translation_on": {"af":"Vertaling aan","ar":"الترجمة مفعلة","ca":"Traducció activada","de":"Übersetzung ein","el":"Μετάφραση ενεργή","fi":"Käännös päällä","fr":"Traduction activée","ga":"Aistriúchán ar siúl","hi":"अनुवाद चालू","hr":"Prijevod uključen","hu":"Fordítás be","id":"Terjemahan aktif","it":"Traduzione attiva","ja":"翻訳オン","ko":"번역 켜짐","nl":"Vertaling aan","no":"Oversettelse på","pl":"Tłumaczenie włączone","pt":"Tradução ativada","ro":"Traducere activată","ru":"Перевод включён","sr":"Превод укључен","sv":"Översättning på","sw":"Tafsiri imewashwa","th":"เปิดการแปล","tr":"Çeviri açık","vi":"Bật dịch","zh-Hans":"翻译已开启","zh-Hant":"翻譯已開啟"},
        "translation_off": {"af":"Vertaling af","ar":"الترجمة معطلة","ca":"Traducció desactivada","de":"Übersetzung aus","el":"Μετάφραση ανενεργή","fi":"Käännös pois","fr":"Traduction désactivée","ga":"Aistriúchán múchta","hi":"अनुवाद बंद","hr":"Prijevod isključen","hu":"Fordítás ki","id":"Terjemahan nonaktif","it":"Traduzione disattivata","ja":"翻訳オフ","ko":"번역 꺼짐","nl":"Vertaling uit","no":"Oversettelse av","pl":"Tłumaczenie wyłączone","pt":"Tradução desativada","ro":"Traducere dezactivată","ru":"Перевод выключен","sr":"Превод искључен","sv":"Översättning av","sw":"Tafsiri imezimwa","th":"ปิดการแปล","tr":"Çeviri kapalı","vi":"Tắt dịch","zh-Hans":"翻译已关闭","zh-Hant":"翻譯已關閉"},
        "translating": {"af":"Vertaal tans…","ar":"جارٍ الترجمة…","ca":"Traduint…","de":"Übersetzung läuft…","el":"Μετάφραση…","fi":"Käännetään…","fr":"Traduction en cours…","ga":"Á aistriú…","hi":"अनुवाद हो रहा है…","hr":"Prevođenje…","hu":"Fordítás…","id":"Menerjemahkan…","it":"Traduzione in corso…","ja":"翻訳中…","ko":"번역 중…","nl":"Vertalen…","no":"Oversetter…","pl":"Tłumaczenie…","pt":"Traduzindo…","ro":"Se traduce…","ru":"Перевод…","sr":"Превођење…","sv":"Översätter…","sw":"Inatafsiri…","th":"กำลังแปล…","tr":"Çevriliyor…","vi":"Đang dịch…","zh-Hans":"翻译中…","zh-Hant":"翻譯中…"},
    },
    "lang": {
        "hak-TW": {"af":"Hakka (Taiwan)","ar":"هاكا (تايوان)","ca":"Hakka (Taiwan)","de":"Hakka (Taiwan)","el":"Χάκα (Ταϊβάν)","fi":"Hakka (Taiwan)","fr":"Hakka (Taïwan)","ga":"Hakka (An Téaváin)","hi":"हक्का (ताइवान)","hr":"Hakka (Tajvan)","hu":"Hakka (Tajvan)","id":"Hakka (Taiwan)","it":"Hakka (Taiwan)","ja":"客家語（台湾）","ko":"하카어 (대만)","nl":"Hakka (Taiwan)","no":"Hakka (Taiwan)","pl":"Hakka (Tajwan)","pt":"Hakka (Taiwan)","ro":"Hakka (Taiwan)","ru":"Хакка (Тайвань)","sr":"Хака (Тајван)","sv":"Hakka (Taiwan)","sw":"Kihakka (Taiwan)","th":"แคะ (ไต้หวัน)","tr":"Hakka (Tayvan)","vi":"Tiếng Khách Gia (Đài Loan)","zh-Hans":"客家语（台湾）","zh-Hant":"客家語（台灣）"},
    },
}

# Additional msg keys
T["msg"].update({
    "find_videos": {"af":"Vind video's op jou vlak","ar":"ابحث عن فيديوهات بمستواك","ca":"Troba vídeos del teu nivell","de":"Finden Sie Videos auf Ihrem Niveau","el":"Βρείτε βίντεο στο επίπεδό σας","fi":"Löydä tasollesi sopivia videoita","fr":"Trouvez des vidéos à votre niveau","ga":"Aimsigh físeáin ag do leibhéal","hi":"अपने स्तर के वीडियो खोजें","hr":"Pronađite videozapise na svojoj razini","hu":"Találjon videókat a saját szintjén","id":"Temukan video sesuai level Anda","it":"Trova video al tuo livello","ja":"自分のレベルに合った動画を見つける","ko":"내 레벨에 맞는 비디오 찾기","nl":"Vind video's op uw niveau","no":"Finn videoer på ditt nivå","pl":"Znajdź filmy na swoim poziomie","pt":"Encontre vídeos no seu nível","ro":"Găsiți videoclipuri la nivelul dvs.","ru":"Найдите видео своего уровня","sr":"Пронађите видео снимке на свом нивоу","sv":"Hitta videor på din nivå","sw":"Tafuta video katika kiwango chako","th":"ค้นหาวิดีโอในระดับของคุณ","tr":"Seviyenize uygun videolar bulun","vi":"Tìm video phù hợp trình độ của bạn","zh-Hans":"找到适合您水平的视频","zh-Hant":"找到適合您程度的影片"},
    "lookup_words": {"af":"Soek woorde op en stoor woordeskat","ar":"ابحث عن الكلمات واحفظ المفردات","ca":"Cerca paraules i desa vocabulari","de":"Wörter nachschlagen & Vokabeln speichern","el":"Αναζητήστε λέξεις και αποθηκεύστε λεξιλόγιο","fi":"Hae sanoja ja tallenna sanastoa","fr":"Recherchez des mots et enregistrez du vocabulaire","ga":"Cuardaigh focail agus sábháil stór focal","hi":"शब्द खोजें और शब्दावली सहेजें","hr":"Potražite riječi i spremite vokabular","hu":"Keressen szavakat és mentse a szókincset","id":"Cari kata & simpan kosakata","it":"Cerca parole e salva il vocabolario","ja":"単語を調べて語彙を保存","ko":"단어 검색 및 어휘 저장","nl":"Zoek woorden op en sla woordenschat op","no":"Slå opp ord og lagre ordforråd","pl":"Sprawdzaj słówka i zapisuj słownictwo","pt":"Consulte palavras e salve vocabulário","ro":"Căutați cuvinte și salvați vocabularul","ru":"Ищите слова и сохраняйте словарь","sr":"Потражите речи и сачувајте речник","sv":"Slå upp ord och spara ordförråd","sw":"Angalia maneno na uhifadhi msamiati","th":"ค้นหาคำศัพท์และบันทึกคำศัพท์","tr":"Kelimelere bakın ve kelime dağarcığınızı kaydedin","vi":"Tra từ và lưu từ vựng","zh-Hans":"查词并保存词汇","zh-Hant":"查詢單字並儲存詞彙"},
    "watch_live": {"af":"Kyk na regstreekse kanale","ar":"مشاهدة القنوات المباشرة","ca":"Veure canals en directe","de":"Live-Kanäle ansehen","el":"Παρακολουθήστε ζωντανά κανάλια","fi":"Katso suoria kanavia","fr":"Regarder les chaînes en direct","ga":"Féach ar bhealaí beo","hi":"लाइव चैनल देखें","hr":"Gledajte kanale uživo","hu":"Élő csatornák nézése","id":"Tonton saluran langsung","it":"Guarda i canali in diretta","ja":"ライブチャンネルを視聴","ko":"실시간 채널 시청","nl":"Live kanalen bekijken","no":"Se direktesendte kanaler","pl":"Oglądaj kanały na żywo","pt":"Assistir canais ao vivo","ro":"Urmăriți canale live","ru":"Смотреть прямые эфиры","sr":"Гледајте канале уживо","sv":"Titta på livekanaler","sw":"Tazama vituo vya moja kwa moja","th":"ดูช่องถ่ายทอดสด","tr":"Canlı kanalları izle","vi":"Xem kênh trực tiếp","zh-Hans":"观看直播频道","zh-Hant":"觀看直播頻道"},
    "customize_experience": {"af":"Pas jou ervaring aan","ar":"خصص تجربتك","ca":"Personalitza la teva experiència","de":"Passen Sie Ihr Erlebnis an","el":"Προσαρμόστε την εμπειρία σας","fi":"Mukauta kokemustasi","fr":"Personnalisez votre expérience","ga":"Saincheap d'eispéireas","hi":"अपने अनुभव को अनुकूलित करें","hr":"Prilagodite svoje iskustvo","hu":"Szabja testre az élményt","id":"Sesuaikan pengalaman Anda","it":"Personalizza la tua esperienza","ja":"体験をカスタマイズ","ko":"경험 맞춤 설정","nl":"Pas uw ervaring aan","no":"Tilpass opplevelsen din","pl":"Dostosuj swoje doświadczenie","pt":"Personalize sua experiência","ro":"Personalizați-vă experiența","ru":"Настройте свой опыт","sr":"Прилагодите своје искуство","sv":"Anpassa din upplevelse","sw":"Geuza uzoefu wako kukufaa","th":"ปรับแต่งประสบการณ์ของคุณ","tr":"Deneyiminizi özelleştirin","vi":"Tùy chỉnh trải nghiệm của bạn","zh-Hans":"自定义您的体验","zh-Hant":"自訂您的體驗"},
    "coming_soon": {"af":"Binnekort beskikbaar","ar":"قريبًا","ca":"Properament","de":"Demnächst verfügbar","el":"Έρχεται σύντομα","fi":"Tulossa pian","fr":"Bientôt disponible","ga":"Ag teacht go luath","hi":"जल्द आ रहा है","hr":"Dolazi uskoro","hu":"Hamarosan","id":"Segera hadir","it":"Prossimamente","ja":"近日公開","ko":"곧 출시됩니다","nl":"Binnenkort beschikbaar","no":"Kommer snart","pl":"Wkrótce","pt":"Em breve","ro":"În curând","ru":"Скоро","sr":"Долази ускоро","sv":"Kommer snart","sw":"Inakuja hivi karibuni","th":"เร็วๆ นี้","tr":"Çok yakında","vi":"Sắp ra mắt","zh-Hans":"即将推出","zh-Hant":"即將推出"},
    "lifetime_only": {"af":"Slegs die lewenslange plan is beskikbaar as 'n Apple-inprogram-aankoopopsie.","ar":"فقط الخطة مدى الحياة متاحة كخيار للشراء داخل التطبيق من Apple.","ca":"Només el pla vitalici està disponible com a opció de compra dins de l'app d'Apple.","de":"Nur der Lifetime-Plan ist als In-App-Kauf bei Apple verfügbar.","el":"Μόνο το ισόβιο πρόγραμμα είναι διαθέσιμο ως επιλογή αγοράς εντός εφαρμογής της Apple.","fi":"Vain elinikäinen sopimus on saatavilla Applen sovelluksen sisäisenä ostovaihtoehtona.","fr":"Seul le plan à vie est disponible en tant qu'option d'achat intégré Apple.","ga":"Níl ach an plean saoil ar fáil mar rogha ceannacháin in-app Apple.","hi":"Apple इन-ऐप खरीदारी के लिए केवल आजीवन योजना उपलब्ध है।","hr":"Samo je doživotni plan dostupan kao opcija kupnje unutar aplikacije Apple.","hu":"Csak az élettartam csomag érhető el Apple alkalmazáson belüli vásárlási lehetőségként.","id":"Hanya paket seumur hidup yang tersedia sebagai opsi pembelian dalam aplikasi Apple.","it":"Solo il piano a vita è disponibile come opzione di acquisto in-app Apple.","ja":"Appleのアプリ内購入では、ライフタイムプランのみが利用可能です。","ko":"Apple 인앱 구매 옵션으로는 평생 플랜만 이용 가능합니다.","nl":"Alleen het levenslange abonnement is beschikbaar als in-app aankoopoptie van Apple.","no":"Kun livstidsplanen er tilgjengelig som kjøpsalternativ i Apple-appen.","pl":"Tylko plan dożywotni jest dostępny jako opcja zakupu w aplikacji Apple.","pt":"Apenas o plano vitalício está disponível como opção de compra no app da Apple.","ro":"Doar planul pe viață este disponibil ca opțiune de achiziție în aplicație Apple.","ru":"Только пожизненный план доступен в качестве встроенной покупки Apple.","sr":"Само је доживотни план доступан као опција куповине унутар апликације Apple.","sv":"Endast livstidsplanen är tillgänglig som köpalternativ i Apple-appen.","sw":"Mpango wa maisha pekee ndio unaopatikana kama chaguo la ununuzi wa ndani ya programu ya Apple.","th":"เฉพาะแผนตลอดชีพเท่านั้นที่มีให้เลือกในการซื้อในแอปของ Apple","tr":"Apple uygulama içi satın alma seçeneği olarak yalnızca Ömür Boyu plan mevcuttur.","vi":"Chỉ có gói trọn đời khả dụng dưới dạng mua trong ứng dụng Apple.","zh-Hans":"Apple 应用内购买仅支持终身计划。","zh-Hant":"Apple 應用內購買僅支援終身計劃。"},
})

# Apply
LANGS = ['af','ar','ca','de','el','fi','fr','ga','hi','hr','hu','id','it','ja',
         'ko','nl','no','pl','pt','ro','ru','sr','sv','sw','th','tr','vi','zh-Hans','zh-Hant']

total = 0
for lang in LANGS:
    path = os.path.join(MSG, f'{lang}.json')
    with open(path, 'r') as f:
        data = json.load(f)
    count = 0
    for cat, keys in T.items():
        if cat not in data:
            data[cat] = {}
        for key, translations in keys.items():
            if lang in translations:
                data[cat][key] = translations[lang]
                count += 1
    with open(path, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
        f.write('\n')
    print(f'  {lang}: {count} keys')
    total += count

print(f'\nTotal: {total} keys across {len(LANGS)} languages')
