// @/contexts/LanguageContext.tsx

import React, { createContext, useContext, useState, useEffect, ReactNode, useMemo } from 'react';
import { I18n } from 'i18n-js';
import Languages from '@/src/languages';
import { Language } from '@/src/languages';  // Import the Language type from your languages module

// Instantiate I18n with the `new` keyword
// Messages loaded from shared packages/shared/locales/ (generated by sync-translations.mjs)
const i18n = new I18n({
  en: require('../../packages/shared/locales/en.json'),
  'zh-Hans': require('../../packages/shared/locales/zh-Hans.json'),
  'zh-Hant': require('../../packages/shared/locales/zh-Hant.json'),
  af: require('../../packages/shared/locales/af.json'),
  ar: require('../../packages/shared/locales/ar.json'),
  ca: require('../../packages/shared/locales/ca.json'),
  de: require('../../packages/shared/locales/de.json'),
  el: require('../../packages/shared/locales/el.json'),
  es: require('../../packages/shared/locales/es.json'),
  fi: require('../../packages/shared/locales/fi.json'),
  fr: require('../../packages/shared/locales/fr.json'),
  ga: require('../../packages/shared/locales/ga.json'),
  hi: require('../../packages/shared/locales/hi.json'),
  hr: require('../../packages/shared/locales/hr.json'),
  hu: require('../../packages/shared/locales/hu.json'),
  id: require('../../packages/shared/locales/id.json'),
  it: require('../../packages/shared/locales/it.json'),
  ja: require('../../packages/shared/locales/ja.json'),
  ko: require('../../packages/shared/locales/ko.json'),
  nl: require('../../packages/shared/locales/nl.json'),
  no: require('../../packages/shared/locales/no.json'),
  pl: require('../../packages/shared/locales/pl.json'),
  pt: require('../../packages/shared/locales/pt.json'),
  ro: require('../../packages/shared/locales/ro.json'),
  ru: require('../../packages/shared/locales/ru.json'),
  sr: require('../../packages/shared/locales/sr.json'),
  sv: require('../../packages/shared/locales/sv.json'),
  sw: require('../../packages/shared/locales/sw.json'),
  th: require('../../packages/shared/locales/th.json'),
  tr: require('../../packages/shared/locales/tr.json'),
  vi: require('../../packages/shared/locales/vi.json')
});

// Enable fallback and load default translations
i18n.enableFallback = true;
i18n.translations.en = i18n.translations.en || require('../../packages/shared/locales/en.json');

// Set default missingBehavior
i18n.missingBehavior = 'guess';

// Define the context's value type
interface LanguageContextType {
  setL1Lang: (lang: Language | null) => void;
  setL2Lang: (lang: Language | null) => void;
  l1Lang: Language | null;
  l2Lang: Language | null;
  languages: Languages | null;
  i18n: I18n;
  t: typeof i18n.t;
}

// Create the context with a default value
const LanguageContext = createContext<LanguageContextType>({
  setL1Lang: () => {},
  setL2Lang: () => {},
  l1Lang: null,
  l2Lang: null,
  languages: null,
  i18n,
  t: i18n.t.bind(i18n)
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [l1Lang, setL1Lang] = useState<Language | null>(null);
  const [l2Lang, setL2Lang] = useState<Language | null>(null);
  const [languages, setLanguages] = useState<Languages | null>(null);

  useEffect(() => {
    const loadLanguages = async () => {
      const langs = await Languages.getInstance();
      setLanguages(langs);
    };

    loadLanguages();
  }, []);

  useEffect(() => {
    if (l1Lang?.code) {
      try {
        i18n.locale = l1Lang.code;
        console.log('Setting locale to', l1Lang.code);
      } catch (error) {
        console.error("Failed to load translations", error);
        i18n.locale = 'en'; // Fallback to English
      }
    }
  }, [l1Lang]);


  // Stable t function — avoids re-running downstream effects on every render
  const t = useMemo(() => i18n.t.bind(i18n), []);

  // Context value that will be exposed to other components
  const value = useMemo(() => ({
    setL1Lang,
    setL2Lang,
    l1Lang,
    l2Lang,
    languages,
    i18n,
    t
  }), [l1Lang, l2Lang, languages, i18n, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
