/**
 * Asset resolution (SPEC-095, ADR-0043).
 *
 * Content stores **relative asset keys** (`u06/B/t2.mp3`), never absolute URLs,
 * so the host behind them can change without touching a single content file.
 * The app supplies the base from its own `ASSET_BASE_URL` constant (mirroring
 * `PYTHON_API_URL`), and this module is the only place that joins the two.
 */

/**
 * Where textbook media is published.
 *
 * One definition, in one place, because the two apps previously drifted: web
 * defaulted to a local path nothing served and mobile pointed at
 * `/data/textbook` rather than the folder that actually exists. Each app still
 * exports its own `ASSET_BASE_URL` (ADR-0043) and reads its own env override —
 * but neither re-types this URL.
 *
 * This directory is the shared host's `data/` root; its siblings are served at
 * `data/char-stroke-svgs/` and `data/word-images/`
 * (`zerotohero-nuxt/lib/utils/servers.js:38-39`).
 */
export const DEFAULT_TEXTBOOK_ASSET_BASE_URL =
  'https://server.chinesezerotohero.com/data/interactive-textbook';

/**
 * Join an asset key onto a base URL.
 *
 * - An already-absolute key (`https://…`, `data:…`) is returned untouched, so
 *   content can still reference an external asset deliberately.
 * - Each path segment is percent-encoded, but `/` separators are preserved.
 * - Trailing/leading slashes on either side are normalised, so a base with or
 *   without a trailing slash behaves identically.
 */
export function resolveAssetKey(baseUrl: string, key: string): string {
  if (!key) return '';
  if (/^(https?:|data:|blob:)/i.test(key)) return key;

  const base = (baseUrl ?? '').replace(/\/+$/, '');
  const path = key.replace(/^\/+/, '');
  if (!base) return `/${path}`;

  const encoded = path
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/');

  return `${base}/${encoded}`;
}

/** A resolver bound to one base URL. */
export function createAssetResolver(baseUrl: string): (key: string) => string {
  return (key: string) => resolveAssetKey(baseUrl, key);
}

export type AssetResolver = (key: string) => string;

/**
 * The media a book needs, as generated by the publish step.
 *
 * `keys` is what the validator checks content against: a content file that
 * references an asset nobody published is a broken exercise, and catching it at
 * validation time is far cheaper than at playback.
 */
export interface AssetManifest {
  book: string;
  /** Base URL the keys were published under, for diagnostics only. */
  baseUrl?: string;
  keys: string[];
}

export function assetKeySet(manifest: AssetManifest | null | undefined): Set<string> {
  return new Set(manifest?.keys ?? []);
}
