#!/usr/bin/env node
/**
 * build-tokens.mts — Generate NativeWind tailwind.config.js + global.css
 *                     from shared design tokens.
 *
 * Usage: npx tsx scripts/build-tokens.mts
 *
 * Reads:  packages/shared/src/tokens.ts (canonical design tokens)
 * Writes: apps/mobile/tailwind.config.js (generated, do not edit manually)
 *         apps/mobile/global.css (generated, do not edit manually)
 *
 * Colors use CSS custom properties (hsl(var(--xxx) / <alpha-value>)) so
 * that NativeWind can resolve them at runtime for light ↔ dark switching,
 * matching the web app's next-themes + CSS variables pattern.
 *
 * Scale: component spacing/font-size/radius intentionally use the DEFAULT
 * Tailwind scale (no overrides) so the mobile UI matches shadcn/ui and the
 * web app's proportions exactly — only colors and fontFamily are customized.
 *
 * ADR-0011 (SUPERSEDED): Mobile design system now follows the web app's
 * CSS variable pattern exactly — no per-component dark: overrides needed.
 * ADR-0010: Port Web to Mobile (see "Styling: NativeWind + shared tokens")
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_PATH = path.resolve(__dirname, '../packages/shared/src/tokens.ts');
const { lightSemantic, darkSemantic, typography } = await import(TOKENS_PATH);

// ── Helpers ────────────────────────────────────

/** camelCase → kebab-case (e.g., primaryForeground → primary-foreground) */
function kebabCase(str: string): string {
  return str.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
}

/** Format a color key — quote it if it contains hyphens (kebab-case). */
function formatKey(key: string): string {
  const k = kebabCase(key);
  return k.includes('-') ? `'${k}'` : k;
}

// ── All semantic color keys (light and dark have the same keys) ──
const semanticKeys = Object.keys(lightSemantic) as (keyof typeof lightSemantic)[];

// ── Generate global.css ────────────────────────
// CSS custom properties with raw HSL channel values (no hsl() wrapper).
// :root = light theme, .dark:root = dark theme.
// Wrapped in @layer base per NativeWind's expected pattern.

const cssVarLines = (tokens: typeof lightSemantic, indent: string) =>
  semanticKeys
    .map((key) => `${indent}--${kebabCase(key)}: ${tokens[key]};`)
    .join('\n');

const globalCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${cssVarLines(lightSemantic, '    ')}
  }

  .dark:root {
${cssVarLines(darkSemantic, '    ')}
  }
}
`;

// ── Generate tailwind.config.js ────────────────
// Colors reference CSS variables via hsl(var(--xxx) / <alpha-value>)
// so opacity modifiers (bg-primary/20) continue to work.

const colorEntries = semanticKeys.map(
  (key) => `        ${formatKey(key)}: 'hsl(var(--${kebabCase(key)}) / <alpha-value>)',`,
);

const fontFamilyEntries = (
  Object.keys(typography.fontFamily) as (keyof typeof typography.fontFamily)[]
).map((key) => `        ${formatKey(key)}: ['${typography.fontFamily[key]}'],`);

const tailwindConfig = `/** @type {import('tailwindcss').Config} */
// ──────────────────────────────────────────────────
// GENERATED by scripts/build-tokens.mts
// Source: packages/shared/src/tokens.ts
// DO NOT EDIT MANUALLY — run "npx tsx scripts/build-tokens.mts" to update
// ──────────────────────────────────────────────────

module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
${colorEntries.join('\n')}
      },
      fontFamily: {
${fontFamilyEntries.join('\n')}
      },
    },
  },
  plugins: [],
};
`;

// ── Write outputs ──

const cssOutPath = path.resolve(__dirname, '../apps/mobile/global.css');
fs.writeFileSync(cssOutPath, globalCss, 'utf-8');
console.log(`✓ Generated ${cssOutPath}`);

const configOutPath = path.resolve(__dirname, '../apps/mobile/tailwind.config.js');
fs.writeFileSync(configOutPath, tailwindConfig, 'utf-8');
console.log(`✓ Generated ${configOutPath}`);
