#!/usr/bin/env node
/**
 * build-tokens.mts — Generate NativeWind tailwind.config.js from shared design tokens.
 *
 * Usage: npx tsx scripts/build-tokens.mts
 *
 * Reads:  packages/shared/src/tokens.ts (canonical design tokens)
 * Writes: apps/mobile-v2/tailwind.config.js (generated, do not edit manually)
 *
 * The generated config uses NativeWind preset + shared HSL color tokens.
 * Uses dark semantic tokens as the default theme (light mode TBD).
 * ADR-0011: Shared Design Tokens
 * ADR-0010: Port Web to Mobile (see "Styling: NativeWind + shared tokens")
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_PATH = path.resolve(__dirname, '../packages/shared/src/tokens');
const { lightSemantic, darkSemantic, typography, spacing, borderRadius } = await import(TOKENS_PATH);

// ── Helpers ────────────────────────────────────

/** camelCase → kebab-case (e.g., primaryForeground → primary-foreground) */
function kebabCase(str: string): string {
  return str.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
}

/** Format a color key — quote it if it contains hyphens (kebab-case). */
function formatKey(key: string): string {
  const k = kebabCase(key);
  return k.includes('-') ? `'${k}'` : k;
}

/** Mobile font sizes render ~12% smaller than web at the same rem value
 *  due to platform font rendering differences. Scale up to match visually. */
const MOBILE_SCALE = 1.25;
function scaleRem(rem: string): string {
  const num = parseFloat(rem);
  if (isNaN(num)) return rem;
  return `${(num * MOBILE_SCALE).toFixed(3)}rem`;
}

// ── Build color maps from semantic tokens ──
// Uses CSS custom properties — light/dark values are defined in global.css
// via :root and .dark selectors, matching the web app's approach.
// NativeWind resolves hsl(var(--...)) at build time.

const colorEntries = Object.keys(lightSemantic).map((key) => {
  const varName = kebabCase(key);
  return `        ${formatKey(key)}: 'hsl(var(--${varName}))',`;
});

// ── Generate config ──

const config = `/** @type {import('tailwindcss').Config} */
// ──────────────────────────────────────────────────
// GENERATED by scripts/build-tokens.mts
// Source: packages/shared/src/tokens.ts
// DO NOT EDIT MANUALLY — run "npx tsx scripts/build-tokens.mts" to update
// ──────────────────────────────────────────────────

module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
${colorEntries.join('\n')}
      },
      fontSize: {
        xs: '${scaleRem(typography.fontSize.xs)}',
        sm: '${scaleRem(typography.fontSize.sm)}',
        base: '${scaleRem(typography.fontSize.base)}',
        lg: '${scaleRem(typography.fontSize.lg)}',
        xl: '${scaleRem(typography.fontSize.xl)}',
        '2xl': '${scaleRem(typography.fontSize['2xl'])}',
        '3xl': '${scaleRem(typography.fontSize['3xl'])}',
        '4xl': '${scaleRem(typography.fontSize['4xl'])}',
        '5xl': '${scaleRem(typography.fontSize['5xl'])}',
      },
      fontWeight: {
        normal: '${typography.fontWeight.normal}',
        bold: '${typography.fontWeight.bold}',
      },
      lineHeight: {
        tight: '${typography.lineHeight.tight}',
        normal: '${typography.lineHeight.normal}',
        relaxed: '${typography.lineHeight.relaxed}',
      },
      spacing: {
        0: '0',
        0.5: '${scaleRem(spacing[0.5])}',
        1: '${scaleRem(spacing[1])}',
        1.5: '${scaleRem(spacing[1.5])}',
        2: '${scaleRem(spacing[2])}',
        2.5: '${scaleRem(spacing[2.5])}',
        3: '${scaleRem(spacing[3])}',
        3.5: '${scaleRem(spacing[3.5])}',
        4: '${scaleRem(spacing[4])}',
        5: '${scaleRem(spacing[5])}',
        6: '${scaleRem(spacing[6])}',
        7: '${scaleRem(spacing[7])}',
        8: '${scaleRem(spacing[8])}',
        9: '${scaleRem(spacing[9])}',
        10: '${scaleRem(spacing[10])}',
        12: '${scaleRem(spacing[12])}',
        16: '${scaleRem(spacing[16])}',
      },
      borderRadius: {
        none: '${borderRadius.none}',
        sm: '${borderRadius.sm}',
        DEFAULT: '${borderRadius.DEFAULT}',
        md: '${borderRadius.md}',
        lg: '${borderRadius.lg}',
        xl: '${borderRadius.xl}',
        full: '${borderRadius.full}',
      },
      fontFamily: {
        sans: ['${typography.fontFamily.sans}'],
        mono: ['${typography.fontFamily.mono}'],
      },
    },
  },
  plugins: [],
};
`;

// ── Write output ──

const outPath = path.resolve(__dirname, '../apps/mobile-v2/tailwind.config.js');
fs.writeFileSync(outPath, config, 'utf-8');
console.log(`✓ Generated ${outPath}`);
