#!/usr/bin/env node
/**
 * build-tokens.mts — Generate NativeWind tailwind.config.js + global.css
 *                     from shared design tokens.
 *
 * Usage: npx tsx scripts/build-tokens.mts
 *
 * Reads:  packages/shared/src/tokens.ts (canonical design tokens)
 * Writes: apps/mobile-v2/tailwind.config.js (generated, do not edit manually)
 *         apps/mobile-v2/global.css (generated, do not edit manually)
 *
 * Colors use CSS custom properties (hsl(var(--xxx) / <alpha-value>)) so
 * that NativeWind can resolve them at runtime for light ↔ dark switching,
 * matching the web app's next-themes + CSS variables pattern.
 *
 * ADR-0011 (SUPERSEDED): Mobile design system now follows the web app's
 * CSS variable pattern exactly — no per-component dark: overrides needed.
 * ADR-0010: Port Web to Mobile (see "Styling: NativeWind + shared tokens")
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_PATH = path.resolve(__dirname, '../packages/shared/src/tokens');
const {
  lightSemantic,
  darkSemantic,
  typography,
  spacing,
  borderRadius,
} = await import(TOKENS_PATH);

// ── Helpers ────────────────────────────────────

/** camelCase → kebab-case (e.g., primaryForeground → primary-foreground) */
function kebabCase(str: string): string {
  return str.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
}

/** Format a color key — quote it if it contains hyphens (kebab-case). */
function formatKey(key: string): string {
  const k = kebabCase(key);
  return k.includes('-') ? `'${k}'` : k;
}

/** Mobile font sizes render ~12% smaller than web at the same rem value
 *  due to platform font rendering differences. Scale up to match visually. */
const MOBILE_SCALE = 1.25;
function scaleRem(rem: string): string {
  const num = parseFloat(rem);
  if (isNaN(num)) return rem;
  return `${(num * MOBILE_SCALE).toFixed(3)}rem`;
}

// ── All semantic color keys (light and dark have the same keys) ──
const semanticKeys = Object.keys(lightSemantic) as (keyof typeof lightSemantic)[];

// ── Generate global.css ────────────────────────
// CSS custom properties with raw HSL channel values (no hsl() wrapper).
// :root = light theme, .dark:root = dark theme.
// Wrapped in @layer base per NativeWind's expected pattern.

const cssVarLines = (tokens: typeof lightSemantic, indent: string) =>
  semanticKeys
    .map((key) => `${indent}--${kebabCase(key)}: ${tokens[key]};`)
    .join('\n');

const globalCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${cssVarLines(lightSemantic, '    ')}
  }

  .dark:root {
${cssVarLines(darkSemantic, '    ')}
  }
}
`;

// ── Generate tailwind.config.js ────────────────
// Colors reference CSS variables via hsl(var(--xxx) / <alpha-value>)
// so opacity modifiers (bg-primary/20) continue to work.

const colorEntries = semanticKeys.map(
  (key) => `        ${formatKey(key)}: 'hsl(var(--${kebabCase(key)}) / <alpha-value>)',`,
);

const tailwindConfig = `/** @type {import('tailwindcss').Config} */
// ──────────────────────────────────────────────────
// GENERATED by scripts/build-tokens.mts
// Source: packages/shared/src/tokens.ts
// DO NOT EDIT MANUALLY — run "npx tsx scripts/build-tokens.mts" to update
// ──────────────────────────────────────────────────

module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
${colorEntries.join('\n')}
      },
      fontSize: {
        xs: '${scaleRem(typography.fontSize.xs)}',
        sm: '${scaleRem(typography.fontSize.sm)}',
        base: '${scaleRem(typography.fontSize.base)}',
        lg: '${scaleRem(typography.fontSize.lg)}',
        xl: '${scaleRem(typography.fontSize.xl)}',
        '2xl': '${scaleRem(typography.fontSize['2xl'])}',
        '3xl': '${scaleRem(typography.fontSize['3xl'])}',
        '4xl': '${scaleRem(typography.fontSize['4xl'])}',
        '5xl': '${scaleRem(typography.fontSize['5xl'])}',
      },
      fontWeight: {
        normal: '${typography.fontWeight.normal}',
        bold: '${typography.fontWeight.bold}',
      },
      lineHeight: {
        tight: '${typography.lineHeight.tight}',
        normal: '${typography.lineHeight.normal}',
        relaxed: '${typography.lineHeight.relaxed}',
      },
      spacing: {
        0: '0',
        0.5: '${scaleRem(spacing[0.5])}',
        1: '${scaleRem(spacing[1])}',
        1.5: '${scaleRem(spacing[1.5])}',
        2: '${scaleRem(spacing[2])}',
        2.5: '${scaleRem(spacing[2.5])}',
        3: '${scaleRem(spacing[3])}',
        3.5: '${scaleRem(spacing[3.5])}',
        4: '${scaleRem(spacing[4])}',
        5: '${scaleRem(spacing[5])}',
        6: '${scaleRem(spacing[6])}',
        7: '${scaleRem(spacing[7])}',
        8: '${scaleRem(spacing[8])}',
        9: '${scaleRem(spacing[9])}',
        10: '${scaleRem(spacing[10])}',
        12: '${scaleRem(spacing[12])}',
        16: '${scaleRem(spacing[16])}',
      },
      borderRadius: {
        none: '${borderRadius.none}',
        sm: '${borderRadius.sm}',
        DEFAULT: '${borderRadius.DEFAULT}',
        md: '${borderRadius.md}',
        lg: '${borderRadius.lg}',
        xl: '${borderRadius.xl}',
        full: '${borderRadius.full}',
      },
      fontFamily: {
        sans: ['${typography.fontFamily.sans}'],
        mono: ['${typography.fontFamily.mono}'],
      },
    },
  },
  plugins: [],
};
`;

// ── Write outputs ──

const cssOutPath = path.resolve(__dirname, '../apps/mobile-v2/global.css');
fs.writeFileSync(cssOutPath, globalCss, 'utf-8');
console.log(`✓ Generated ${cssOutPath}`);

const configOutPath = path.resolve(__dirname, '../apps/mobile-v2/tailwind.config.js');
fs.writeFileSync(configOutPath, tailwindConfig, 'utf-8');
console.log(`✓ Generated ${configOutPath}`);
