/** @type {import('tailwindcss').Config} */
// ──────────────────────────────────────────────────
// GENERATED by scripts/build-tokens.mts
// Source: packages/shared/src/tokens.ts
// DO NOT EDIT MANUALLY — run "npx tsx scripts/build-tokens.mts" to update
// ──────────────────────────────────────────────────

module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        success: 'hsl(var(--success))',
        'success-foreground': 'hsl(var(--success-foreground))',
        warning: 'hsl(var(--warning))',
        'warning-foreground': 'hsl(var(--warning-foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      fontSize: {
        xs: '0.938rem',
        sm: '1.094rem',
        base: '1.250rem',
        lg: '1.406rem',
        xl: '1.563rem',
        '2xl': '1.875rem',
        '3xl': '2.344rem',
        '4xl': '2.813rem',
        '5xl': '3.750rem',
      },
      fontWeight: {
        normal: '400',
        bold: '700',
      },
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        relaxed: '1.75',
      },
      spacing: {
        0: '0',
        0.5: '0.156rem',
        1: '0.313rem',
        1.5: '0.469rem',
        2: '0.625rem',
        2.5: '0.781rem',
        3: '0.938rem',
        3.5: '1.094rem',
        4: '1.250rem',
        5: '1.563rem',
        6: '1.875rem',
        7: '2.188rem',
        8: '2.500rem',
        9: '2.813rem',
        10: '3.125rem',
        12: '3.750rem',
        16: '5.000rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        DEFAULT: '0.75rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter'],
        mono: ['JetBrains Mono'],
      },
    },
  },
  plugins: [],
};
