/** @type {import('tailwindcss').Config} */
// ──────────────────────────────────────────────────
// GENERATED by scripts/build-tokens.mts
// Source: packages/shared/src/tokens.ts
// DO NOT EDIT MANUALLY — run "npx tsx scripts/build-tokens.mts" to update
// ──────────────────────────────────────────────────

module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(230 30% 8%)',
        foreground: 'hsl(0 0% 95%)',
        card: 'hsl(230 25% 12%)',
        'card-foreground': 'hsl(0 0% 95%)',
        popover: 'hsl(230 25% 12%)',
        'popover-foreground': 'hsl(0 0% 95%)',
        primary: 'hsl(228 74% 65%)',
        'primary-foreground': 'hsl(0 0% 100%)',
        secondary: 'hsl(230 20% 18%)',
        'secondary-foreground': 'hsl(0 0% 95%)',
        muted: 'hsl(230 20% 18%)',
        'muted-foreground': 'hsl(215 14% 56%)',
        accent: 'hsl(24 100% 58%)',
        'accent-foreground': 'hsl(0 0% 100%)',
        destructive: 'hsl(0 72% 51%)',
        'destructive-foreground': 'hsl(0 0% 100%)',
        success: 'hsl(142 71% 45%)',
        'success-foreground': 'hsl(0 0% 100%)',
        warning: 'hsl(38 92% 50%)',
        'warning-foreground': 'hsl(0 0% 100%)',
        border: 'hsl(230 20% 22%)',
        input: 'hsl(230 20% 22%)',
        ring: 'hsl(228 74% 65%)',
      },
      fontSize: {
        xs: '0.938rem',
        sm: '1.094rem',
        base: '1.250rem',
        lg: '1.406rem',
        xl: '1.563rem',
        '2xl': '1.875rem',
        '3xl': '2.344rem',
        '4xl': '2.813rem',
        '5xl': '3.750rem',
      },
      fontWeight: {
        normal: '400',
        bold: '700',
      },
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        relaxed: '1.75',
      },
      spacing: {
        0: '0',
        0.5: '0.156rem',
        1: '0.313rem',
        1.5: '0.469rem',
        2: '0.625rem',
        2.5: '0.781rem',
        3: '0.938rem',
        3.5: '1.094rem',
        4: '1.250rem',
        5: '1.563rem',
        6: '1.875rem',
        7: '2.188rem',
        8: '2.500rem',
        9: '2.813rem',
        10: '3.125rem',
        12: '3.750rem',
        16: '5.000rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        DEFAULT: '0.75rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter'],
        mono: ['JetBrains Mono'],
      },
    },
  },
  plugins: [],
};
